module.exports = {
    PORT: 3000,
    DEVELOPMENT_LOGGER_LEVEL: 'info',
    PRODUCTION_LOGGER_LEVEL: 'info',
    DB_URL: process.env.DB_URL,
    DB_NAME: process.env.DB_NAME,
    BCRYPT_SALT_ROUNDS: Number(process.env.BCRYPT_SALT_ROUNDS),
    JWT_ACCESS_TOKEN_SECRETE: process.env.JWT_ACCESS_SECRETE,
    JWT_REFRESH_TOKEN_SECRETE: process.env.JWT_REFRESH_SECRETE,
    JWT_ACCESS_TOKEN_EXPIRY: '1m',
    JWT_REFRESH_TOKEN_EXPIRT: '7d',
    REFRESH_COOKIE_EXPIRY: 604800000,
    NODE_ENV: process.env.NODE_ENV,
    ORIGIN_DOMAIN: '*',
    HTTP_METHODS: ['GET', 'POST']
}
